-- 1. Enable pgvector extension (required for RAG and BGE-Large)
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Table to store compliance audits (LangGraph Agent)
CREATE TABLE public.compliance_audits (
    id bigint generated by default as identity primary key,
    report_id uuid not null unique,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    audit_hash text not null unique,
    verdict text not null,
    risk_score integer not null,
    rationale text not null,
    vision_report jsonb not null,
    legal_rationale jsonb not null,
    polygon_area_ha numeric not null,
    crop_type text not null,
    harvest_date date not null,
    invoice_id text not null,
    reported_tons numeric not null
);

-- Configure RLS (Row Level Security) for compliance_audits table
ALTER TABLE public.compliance_audits ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public insert" ON public.compliance_audits FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public read" ON public.compliance_audits FOR SELECT USING (true);


-- 3. Table to store EUDR law embeddings (RAG Context)
CREATE TABLE public.eudr_documents (
    id bigint generated by default as identity primary key,
    content text not null,
    embedding vector(1024) -- Dimension 1024 corresponds to bge-large
);

-- Configure RLS for eudr_documents table
ALTER TABLE public.eudr_documents ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public insert" ON public.eudr_documents FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public read" ON public.eudr_documents FOR SELECT USING (true);


-- 4. Cosine similarity search function (used by SupabaseService RAG)
CREATE OR REPLACE FUNCTION match_eudr_docs (
    query_embedding vector(1024),
    match_count int DEFAULT 4
) RETURNS TABLE (
    content text,
    similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        eudr_documents.content,
        1 - (eudr_documents.embedding <=> query_embedding) AS similarity
    FROM eudr_documents
    ORDER BY eudr_documents.embedding <=> query_embedding
    LIMIT match_count;
END;
$$;
